# Generated by Django 3.2 on 2022-10-31 11:32

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(default='your name', max_length=150)),
                ('slug', models.CharField(default='slug', max_length=200, validators=[catalog.validators.validate_slug])),
                ('weight', models.IntegerField(default=100, validators=[catalog.validators.validate_weight])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='your name', max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.CharField(default='slug', max_length=200, validators=[catalog.validators.validate_slug])),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='your desc', validators=[catalog.validators.validate_desc]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='your name', max_length=150),
        ),
    ]
