# Generated by Django 3.2 on 2022-11-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('pictures', models.ImageField(default='nothing', upload_to='uploads/%Y/%m')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.descriptionimages'),
        ),
    ]
