# Generated by Django 3.2.4 on 2022-11-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_item_is_on_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items', 'ordering': ('category',), 'verbose_name': 'товары'},
        ),
    ]
